-- MySQL Script generated by MySQL Workbench
-- 10/08/15 19:49:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` INT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Description` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idProduct`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `idOrder` INT NULL AUTO_INCREMENT COMMENT '',
  `Date` DATE NULL COMMENT '',
  `Status` INT NULL COMMENT '',
  PRIMARY KEY (`idOrder`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DrugStore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DrugStore` (
  `idDrugStore` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Address` VARCHAR(45) NULL COMMENT '',
  `Telephone` VARCHAR(45) NULL COMMENT '',
  `Email` VARCHAR(45) NULL COMMENT '',
  `Latitud` VARCHAR(45) NULL COMMENT '',
  `Longitud` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idDrugStore`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_DrugStore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_DrugStore` (
  `idProduct_DrugStore` INT NOT NULL COMMENT '',
  `idProduct` INT NULL COMMENT '',
  `idDrugStore` INT NULL COMMENT '',
  `Price` FLOAT NULL COMMENT '',
  PRIMARY KEY (`idProduct_DrugStore`)  COMMENT '',
  INDEX `idProduct_FK_idx` (`idProduct` ASC)  COMMENT '',
  INDEX `idDrugStore_FK_idx` (`idDrugStore` ASC)  COMMENT '',
  CONSTRAINT `idProduct_FK`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDrugStore_FK`
    FOREIGN KEY (`idDrugStore`)
    REFERENCES `mydb`.`DrugStore` (`idDrugStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_Detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_Detail` (
  `idOrder_Detail` INT NOT NULL COMMENT '',
  `idProdut_DrugStore` INT NULL COMMENT '',
  `Price` VARCHAR(45) NULL COMMENT '',
  `idOrder` INT NULL COMMENT '',
  PRIMARY KEY (`idOrder_Detail`)  COMMENT '',
  INDEX `idProduct_DrugStore_idx` (`idProdut_DrugStore` ASC)  COMMENT '',
  INDEX `idOrder_idx` (`idOrder` ASC)  COMMENT '',
  CONSTRAINT `idProduct_DrugStore`
    FOREIGN KEY (`idProdut_DrugStore`)
    REFERENCES `mydb`.`Product_DrugStore` (`idProduct_DrugStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `LastName` VARCHAR(45) NULL COMMENT '',
  `Email` VARCHAR(45) NULL COMMENT '',
  `Address` VARCHAR(45) NULL COMMENT '',
  `Create_date` DATE NULL COMMENT '',
  PRIMARY KEY (`idUser`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
